### ISSUE TITLE
feat: Milestones

### ISSUE THREAD

**Issue by noonien** [MichaelMure/git-bug#275] opened 2019-12-15 20:58 UTC
It would be really useful to have milestones.

**Comment by MichaelMure** [comment] 2019-12-15 21:21
There sort of is: https://github.com/MichaelMure/git-bug/milestones

Yes, those are short term milestones. This is because this project is developed only by volunteer with variable energy, dedication and time. The set of volunteer itself is variable. There is no point in planning further than that.

You are more than welcome to push forward the thing you care about though.

**Comment by noonien** [comment] 2019-12-16 00:21
Hehe, no, i mean, milestones in git-bug itself.

**Comment by MichaelMure** [comment] 2019-12-16 00:23
... hooo :-D

Haha, hrmmm, ok then ;-)

**Comment by vtexier** [comment] 2020-11-13 10:15
Milestone feature might be like the tag feature to implement, with the exception that you can have only one milestone on an issue.

And may be that you can open/close milestones to get rid of the old ones on display...

**Comment by MichaelMure** [comment] 2022-11-20 17:12
Closing as duplicate of #639

**Closed by MichaelMure** 2022-11-20 17:12 UTC
Labels: enhancement
