### ISSUE TITLE
feat: Branch reviews

### ISSUE THREAD

**Issue by theduke** [MichaelMure/git-bug#17] opened 2018-08-17 23:25 UTC
This is a really cool project.

The next step for me would be to support branch reviews with discussions to replace merge requests.
Do you have any plans for this?

The rough features needed would be:
* multi-user discussions on changesets within files
* marking a change as "needs improvements"
* Resolving discussions and improvement requests
* Marking a commit as approved

ps: I'm happy to help out with this if you see this within the project scope.

**Comment by theduke** [comment] 2018-08-17 23:33
I just discovered https://github.com/google/git-appraise, which is what this would be.

Depending on the storage model etc it probably doesn't make too much sense to duplicate all of this functionality, but rather have possible integration with git-appraise.
Especially on the UI part.

So one approach could be to add a  git-appraise view in the webui.

**Comment by yrashk** [comment] 2018-08-18 03:49
In [SIT](https://sit.fyi), we're just including `git format-patch` files into issues to do merge requests and discussions can go on there. We don't have a way to comment on specific lines, but this is just a matter of designating some kind of referencing convention for comment records.

Maybe this can be of some use/inspiration here?

**Comment by hab25** [comment] 2022-08-21 14:43
> In [SIT](https://sit.fyi), we're just including `git format-patch` files into issues to do merge requests

Did you automate the enforcement of constraints such as required minimum number of approvals? If so, how?

**Comment by MichaelMure** [comment] 2022-11-20 16:50
Closing as duplicate of #373

**Closed by MichaelMure** 2022-11-20 16:50 UTC
