### ISSUE TITLE
Feature: Kanban support

### ISSUE THREAD

**Issue by 0xAlcibiades** [MichaelMure/git-bug#717] opened 2021-10-26 21:04 UTC
Is there a desire for a kanban view in either the termui or web ui for distributed project management?

**Comment by GlancingMind** [comment] 2021-11-03 11:11
Just for reference https://github.com/MichaelMure/git-bug/issues/637

**Comment by MichaelMure** [comment] 2022-11-20 16:05
This is being worked on in https://github.com/MichaelMure/git-bug/pull/843

**Comment by MichaelMure** [comment] 2022-11-20 16:05
Closing as duplicate of #637

**Closed by MichaelMure** 2022-11-20 16:05 UTC
